name: Run linting

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: "package.json"
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
